const data = {
  products: [
    {
      name: 'nike shirt',
      slug: 'nike slem',
      category: 'shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReiews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'nike pant',
      slug: 'nike slom',
      category: 'shirts',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReiews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'nike hat',
      slug: 'nike slam',
      category: 'shirts',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReiews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'nike mat',
      slug: 'nike slim',
      category: 'shirts',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReiews: 10,
      description: 'high quality shirt',
    },
  ],
};
export default data;
